#
# This file generates the sidebar/toctree for all Docs projects and should
# be copied to each project when it is updated
# .. include:: _sidebar.rst.inc
# @Anthony: this can be safely removed if not necessary - it's just a porting of
# https://github.com/robotpy/robotpy-docs/blob/master/gensidebar.py
#

import os

def write_if_changed(fname, contents):
    
    try:
        with open(fname, 'r') as fp:
            old_contents = fp.read()
    except:
        old_contents = ''
        
    if old_contents != contents:
        with open(fname, 'w') as fp:
            fp.write(contents)

def generate_sidebar(conf):
    
    # determine 'latest' or 'stable'
    # if not conf.do_gen:
    do_gen = os.environ.get('SIDEBAR', None) == '1' or conf['on_rtd']
    version = conf['rtd_version']
    
    lines = [
        '', '.. DO NOT MODIFY! THIS PAGE IS AUTOGENERATED!', ''
    ]
    
    def toctree(name):
        lines.extend(['.. toctree::',
                      '    :caption: %s' % name,
                      '    :maxdepth: 2',
                      ''])
    
    def endl():
        lines.append('')
    
    def write(project, desc):
        if do_gen:
            args = desc, project, version
            lines.append('    %s <http://template-super.readthedocs.io/projects/%s/en/%s/>' % args)
    
    #
    # Specify the sidebar contents here
    #
    
    toctree('Sub Projects')
    write('template-sub', 'Template Sub')
    endl()
    
    write_if_changed('_sidebar.rst.inc', '\n'.join(lines))